export const departamentos = [
  "Amazonas",
  "Ancash",
  "Apurimac",
  "Arequipa",
  "Ayacucho",
  "Cajamarca",
  "Cusco",
  "Huancavelica",
  "Huanuco",
  "Ica",
  "Junin",
  "La Libertad",
  "Lambayeque",
  "Lima",
  "Loreto",
  "Madre de Dios",
  "Moquegua",
  "Pasco",
  "Piura",
  "Puno",
  "San Martin",
  "Tacna",
  "Tumbes",
  "Ucayali",
] as const;
export const provincias = [
  "Bagua",
  "Bongara",
  "Chachapoyas",
  "Condorcanqui",
  "Luya",
  "Rodriguez de Mendoza",
  "Utcubamba",
  "Aija",
  "Antonio Raymondi",
  "Asuncion",
  "Bolognesi",
  "Carhuaz",
  "Carlos Fermin Fitzcarrald",
  "Casma",
  "Corongo",
  "Huaraz",
  "Huari",
  "Huarmey",
  "Huaylas",
  "Mariscal Luzuriaga",
  "Ocros",
  "Pallasca",
  "Pomabamba",
  "Recuay",
  "Santa",
  "Sihuas",
  "Yungay",
  "Abancay",
  "Andahuaylas",
  "Antabamba",
  "Aymaraes",
  "Chincheros",
  "Cotabambas",
  "Grau",
  "Arequipa",
  "Camana",
  "Caraveli",
  "Castilla",
  "Caylloma",
  "Condesuyos",
  "Islay",
  "La Union",
  "Cangallo",
  "Huamanga",
  "Huanca Sancos",
  "Huanta",
  "La Mar",
  "Lucanas",
  "Parinacochas",
  "Paucar del Sara Sara",
  "Sucre",
  "Victor Fajardo",
  "Vilcas Huaman",
  "Cajabamba",
  "Cajamarca",
  "Celendin",
  "Chota",
  "Contumaza",
  "Cutervo",
  "Hualgayoc",
  "Jaen",
  "San Ignacio",
  "San Marcos",
  "San Miguel",
  "San Pablo",
  "Santa Cruz",
  "Acomayo",
  "Anta",
  "Calca",
  "Canas",
  "Canchis",
  "Chumbivilcas",
  "Cusco",
  "Espinar",
  "La Convencion",
  "Paruro",
  "Paucartambo",
  "Quispicanchi",
  "Urubamba",
  "Acobamba",
  "Angaraes",
  "Castrovirreyna",
  "Churcampa",
  "Huancavelica",
  "Huaytara",
  "Tayacaja",
  "Ambo",
  "Dos de Mayo",
  "Huacaybamba",
  "Huamalies",
  "Huanuco",
  "Lauricocha",
  "Leoncio Prado",
  "Maraqon",
  "Pachitea",
  "Puerto Inca",
  "Yarowilca",
  "Chincha",
  "Ica",
  "Nazca",
  "Palpa",
  "Pisco",
  "Chanchamayo",
  "Chupaca",
  "Concepcion",
  "Huancayo",
  "Jauja",
  "Junin",
  "Satipo",
  "Tarma",
  "Yauli",
  "Ascope",
  "Bolivar",
  "Chepen",
  "Gran Chimu",
  "Julcan",
  "Otuzco",
  "Pacasmayo",
  "Pataz",
  "Sanchez Carrion",
  "Santiago de Chuco",
  "Trujillo",
  "Viru",
  "Chiclayo",
  "Ferreqafe",
  "Lambayeque",
  "Barranca",
  "Cajatambo",
  "Callao",
  "Cañete",
  "Canta",
  "Huaral",
  "Huarochiri",
  "Huaura",
  "Lima",
  "Oyon",
  "Yauyos",
  "Alto Amazonas",
  "Loreto",
  "Mariscal Ramon Castilla",
  "Maynas",
  "Requena",
  "Ucayali",
  "Manu",
  "Tahuamanu",
  "Tambopata",
  "General Sanchez Cerro",
  "Ilo",
  "Mariscal Nieto",
  "Daniel Alcides Carrion",
  "Oxapampa",
  "Pasco",
  "Ayabaca",
  "Huancabamba",
  "Morropon",
  "Paita",
  "Piura",
  "Sechura",
  "Sullana",
  "Talara",
  "Azangaro",
  "Carabaya",
  "Chucuito",
  "El Collao",
  "Huancane",
  "Lampa",
  "Melgar",
  "Moho",
  "Puno",
  "San Antonio de Putina",
  "San Roman",
  "Sandia",
  "Yunguyo",
  "Bellavista",
  "El Dorado",
  "Huallaga",
  "Lamas",
  "Mariscal Caceres",
  "Moyobamba",
  "Picota",
  "Rioja",
  "San Martin",
  "Tocache",
  "Candarave",
  "Jorge Basadre",
  "Tacna",
  "Tarata",
  "Contralmirante Villar",
  "Tumbes",
  "Zarumilla",
  "Atalaya",
  "Coronel Portillo",
  "Padre Abad",
  "Purus",
] as const;
export const distritos = [
  "Aramango",
  "Copallin",
  "El Parco",
  "Imaza",
  "La Peca",
  "Chisquilla",
  "Churuja",
  "Corosha",
  "Cuispes",
  "Florida",
  "Jazan",
  "Jumbilla",
  "Recta",
  "San Carlos",
  "Shipasbamba",
  "Valera",
  "Yambrasbamba",
  "Asuncion",
  "Balsas",
  "Chachapoyas",
  "Cheto",
  "Chiliquin",
  "Chuquibamba",
  "Granada",
  "Huancas",
  "La Jalca",
  "Leimebamba",
  "Levanto",
  "Magdalena",
  "Mariscal Castilla",
  "Molinopampa",
  "Montevideo",
  "Olleros",
  "Quinjalca",
  "San Francisco de Daguas",
  "San Isidro de Maino",
  "Soloco",
  "Sonche",
  "El Cenepa",
  "Nieva",
  "Rio Santiago",
  "Camporredondo",
  "Cocabamba",
  "Colcamar",
  "Conila",
  "Inguilpata",
  "Lamud",
  "Longuita",
  "Lonya Chico",
  "Luya",
  "Luya Viejo",
  "Maria",
  "Ocalli",
  "Ocumal",
  "Pisuquia",
  "Providencia",
  "San Cristobal",
  "San Francisco del Yeso",
  "San Jeronimo",
  "San Juan de Lopecancha",
  "Santa Catalina",
  "Santo Tomas",
  "Tingo",
  "Trita",
  "Chirimoto",
  "Cochamal",
  "Huambo",
  "Limabamba",
  "Longar",
  "Mariscal Benavides",
  "Milpuc",
  "Omia",
  "San Nicolas",
  "Santa Rosa",
  "Totora",
  "Vista Alegre",
  "Bagua Grande",
  "Cajaruro",
  "Cumba",
  "El Milagro",
  "Jamalca",
  "Lonya Grande",
  "Yamon",
  "Aija",
  "Coris",
  "Huacllan",
  "La Merced",
  "Succha",
  "Aczo",
  "Chaccho",
  "Chingas",
  "Llamellin",
  "Mirgas",
  "San Juan de Rontoy",
  "Acochaca",
  "Chacas",
  "Abelardo Pardo Lezameta",
  "Antonio Raymondi",
  "Aquia",
  "Cajacay",
  "Canis",
  "Chiquian",
  "Colquioc",
  "Huallanca",
  "Huasta",
  "Huayllacayan",
  "La Primavera",
  "Mangas",
  "Pacllon",
  "San Miguel de Corpanqui",
  "Ticllos",
  "Acopampa",
  "Amashca",
  "Anta",
  "Ataquero",
  "Carhuaz",
  "Marcara",
  "Pariahuanca",
  "San Miguel de Aco",
  "Shilla",
  "Tinco",
  "Yungar",
  "San Luis",
  "Yauya",
  "Buena Vista Alta",
  "Casma",
  "Comandante Noel",
  "Yautan",
  "Aco",
  "Bambas",
  "Corongo",
  "Cusca",
  "La Pampa",
  "Yanac",
  "Yupan",
  "Cochabamba",
  "Colcabamba",
  "Huanchay",
  "Huaraz",
  "Independencia",
  "Jangas",
  "La Libertad",
  "Pampas",
  "Pariacoto",
  "Pira",
  "Tarica",
  "Anra",
  "Cajay",
  "Chavin de Huantar",
  "Huacachi",
  "Huacchis",
  "Huachis",
  "Huantar",
  "Huari",
  "Masin",
  "Paucas",
  "Ponto",
  "Rahuapampa",
  "Rapayan",
  "San Marcos",
  "San Pedro de Chana",
  "Uco",
  "Cochapeti",
  "Culebras",
  "Huarmey",
  "Huayan",
  "Malvas",
  "Caraz",
  "Huata",
  "Huaylas",
  "Mato",
  "Pamparomas",
  "Pueblo Libre",
  "Santa Cruz",
  "Santo Toribio",
  "Yuracmarca",
  "Casca",
  "Eleazar Guzman Barron",
  "Fidel Olivas Escudero",
  "Llama",
  "Llumpa",
  "Lucma",
  "Musga",
  "Piscobamba",
  "Acas",
  "Cajamarquilla",
  "Carhuapampa",
  "Cochas",
  "Congas",
  "Llipa",
  "Ocros",
  "San Cristobal de Rajan",
  "San Pedro",
  "Santiago de Chilcas",
  "Bolognesi",
  "Cabana",
  "Conchucos",
  "Huacaschuque",
  "Huandoval",
  "Lacabamba",
  "Llapo",
  "Pallasca",
  "Tauca",
  "Huayllan",
  "Parobamba",
  "Pomabamba",
  "Quinuabamba",
  "Catac",
  "Cotaparaco",
  "Huayllapampa",
  "Llacllin",
  "Marca",
  "Pampas Chico",
  "Pararin",
  "Recuay",
  "Tapacocha",
  "Ticapampa",
  "Caceres del Peru",
  "Chimbote",
  "Coishco",
  "Macate",
  "Moro",
  "Nepeqa",
  "Nuevo Chimbote",
  "Samanco",
  "Santa",
  "Acobamba",
  "Alfonso Ugarte",
  "Cashapampa",
  "Chingalpo",
  "Huayllabamba",
  "Quiches",
  "Ragash",
  "San Juan",
  "Sicsibamba",
  "Sihuas",
  "Cascapara",
  "Mancos",
  "Matacoto",
  "Quillo",
  "Ranrahirca",
  "Shupluy",
  "Yanama",
  "Yungay",
  "Abancay",
  "Chacoche",
  "Circa",
  "Curahuasi",
  "Huanipaca",
  "Lambrama",
  "Pichirhua",
  "San Pedro de Cachora",
  "Tamburco",
  "Andahuaylas",
  "Andarapa",
  "Chiara",
  "Huancarama",
  "Huancaray",
  "Huayana",
  "Kaquiabamba",
  "Kishuara",
  "Pacobamba",
  "Pacucha",
  "Pampachiri",
  "Pomacocha",
  "San Antonio de Cachi",
  "San Miguel de Chaccrampa",
  "Santa Maria de Chicmo",
  "Talavera",
  "Tumay Huaraca",
  "Turpo",
  "Antabamba",
  "El Oro",
  "Huaquirca",
  "Juan Espinoza Medrano",
  "Oropesa",
  "Pachaconas",
  "Sabaino",
  "Capaya",
  "Caraybamba",
  "Chalhuanca",
  "Chapimarca",
  "Cotaruse",
  "Huayllo",
  "Justo Apu Sahuaraura",
  "Lucre",
  "Pocohuanca",
  "San Juan de Chacqa",
  "Saqayca",
  "Soraya",
  "Tapairihua",
  "Tintay",
  "Toraya",
  "Yanaca",
  "Anco-Huallo",
  "Chincheros",
  "Cocharcas",
  "Huaccana",
  "Ocobamba",
  "Ongoy",
  "Ranracancha",
  "Uranmarca",
  "Challhuahuacho",
  "Cotabambas",
  "Coyllurqui",
  "Haquira",
  "Mara",
  "Tambobamba",
  "Chuquibambilla",
  "Curasco",
  "Curpahuasi",
  "Gamarra",
  "Huayllati",
  "Mamara",
  "Micaela Bastidas",
  "Pataypampa",
  "Progreso",
  "San Antonio",
  "Turpay",
  "Vilcabamba",
  "Virundo",
  "Alto Selva Alegre",
  "Arequipa",
  "Cayma",
  "Cerro Colorado",
  "Characato",
  "Chiguata",
  "Jacobo Hunter",
  "Jose Luis Bustamante y Rivero",
  "La Joya",
  "Mariano Melgar",
  "Miraflores",
  "Mollebaya",
  "Paucarpata",
  "Pocsi",
  "Polobaya",
  "Quequeqa",
  "Sabandia",
  "Sachaca",
  "San Juan de Siguas",
  "San Juan de Tarucani",
  "Santa Isabel de Siguas",
  "Santa Rita de Siguas",
  "Socabaya",
  "Tiabaya",
  "Uchumayo",
  "Vitor",
  "Yanahuara",
  "Yarabamba",
  "Yura",
  "Camana",
  "Jose Maria Quimper",
  "Mariano Nicolas Valcarcel",
  "Mariscal Caceres",
  "Nicolas de Pierola",
  "Ocoqa",
  "Quilca",
  "Samuel Pastor",
  "Acari",
  "Atico",
  "Atiquipa",
  "Bella Union",
  "Cahuacho",
  "Caraveli",
  "Chala",
  "Chaparra",
  "Huanuhuanu",
  "Jaqui",
  "Lomas",
  "Quicacha",
  "Yauca",
  "Andagua",
  "Aplao",
  "Ayo",
  "Chachas",
  "Chilcaymarca",
  "Choco",
  "Huancarqui",
  "Machaguay",
  "Majes",
  "Orcopampa",
  "Pampacolca",
  "Tipan",
  "Uqon",
  "Uraca",
  "Viraco",
  "Yanque",
  "Achoma",
  "Cabanaconde",
  "Callalli",
  "Caylloma",
  "Chivay",
  "Coporaque",
  "Huanca",
  "Ichupampa",
  "Lari",
  "Lluta",
  "Maca",
  "Madrigal",
  "San Antonio de Chuca",
  "Sibayo",
  "Tapay",
  "Tisco",
  "Tuti",
  "Andaray",
  "Cayarani",
  "Chichas",
  "Iray",
  "Rio Grande",
  "Salamanca",
  "Yanaquihua",
  "Cocachacra",
  "Dean Valdivia",
  "Islay",
  "Mejia",
  "Mollendo",
  "Punta de Bombon",
  "Alca",
  "Charcana",
  "Cotahuasi",
  "Huaynacotas",
  "Pampamarca",
  "Puyca",
  "Quechualla",
  "Sayla",
  "Tauria",
  "Tomepampa",
  "Toro",
  "Cangallo",
  "Chuschi",
  "Los Morochucos",
  "Maria Parado de Bellido",
  "Paras",
  "Totos",
  "Acocro",
  "Acos Vinchos",
  "Ayacucho",
  "Carmen Alto",
  "Jesús Nazareno",
  "Pacaycasa",
  "Quinua",
  "San Jose de Ticllas",
  "San Juan Bautista",
  "Santiago de Pischa",
  "Socos",
  "Tambillo",
  "Vinchos",
  "Carapo",
  "Sacsamarca",
  "Sancos",
  "Santiago de Lucanamarca",
  "Ayahuanco",
  "Huamanguilla",
  "Huanta",
  "Iguain",
  "Llochegua",
  "Luricocha",
  "Santillana",
  "Sivia",
  "Anco",
  "Ayna",
  "Chilcas",
  "Chungui",
  "Luis Carranza",
  "San Miguel",
  "Tambo",
  "Aucara",
  "Carmen Salcedo",
  "Chaviqa",
  "Chipao",
  "Huac-Huas",
  "Laramate",
  "Leoncio Prado",
  "Llauta",
  "Lucanas",
  "Ocaqa",
  "Otoca",
  "Puquio",
  "Saisa",
  "San Pedro de Palco",
  "Santa Ana de Huaycahuacho",
  "Santa Lucia",
  "Chumpi",
  "Coracora",
  "Coronel Castaqeda",
  "Pacapausa",
  "Pullo",
  "Puyusca",
  "San Francisco de Ravacayco",
  "Upahuacho",
  "Colta",
  "Corculla",
  "Lampa",
  "Marcabamba",
  "Oyolo",
  "Pararca",
  "Pausa",
  "San Javier de Alpabamba",
  "San Jose de Ushua",
  "Sara Sara",
  "Belen",
  "Chalcos",
  "Chilcayoc",
  "Huacaqa",
  "Morcolla",
  "Paico",
  "Querobamba",
  "San Pedro de Larcay",
  "San Salvador de Quije",
  "Santiago de Paucaray",
  "Soras",
  "Alcamenca",
  "Apongo",
  "Asquipata",
  "Canaria",
  "Cayara",
  "Colca",
  "Huamanquiquia",
  "Huancapi",
  "Huancaraylla",
  "Huaya",
  "Sarhua",
  "Vilcanchos",
  "Accomarca",
  "Carhuanca",
  "Concepcion",
  "Huambalpa",
  "Saurama",
  "Vilcas Huaman",
  "Vischongo",
  "Cachachi",
  "Cajabamba",
  "Condebamba",
  "Sitacocha",
  "Cajamarca",
  "Chetilla",
  "Cospan",
  "Encaqada",
  "Jesus",
  "Llacanora",
  "Los Baqos del Inca",
  "Matara",
  "Namora",
  "Celendin",
  "Chumuch",
  "Cortegana",
  "Huasmin",
  "Jorge Chavez",
  "Jose Galvez",
  "La Libertad de Pallan",
  "Miguel Iglesias",
  "Oxamarca",
  "Sorochuco",
  "Sucre",
  "Utco",
  "Anguia",
  "Chadin",
  "Chalamarca",
  "Chiguirip",
  "Chimban",
  "Choropampa",
  "Chota",
  "Conchan",
  "Huambos",
  "Lajas",
  "Miracosta",
  "Paccha",
  "Pion",
  "Querocoto",
  "San Juan de Licupis",
  "Tacabamba",
  "Tocmoche",
  "Chilete",
  "Contumaza",
  "Cupisnique",
  "Guzmango",
  "San Benito",
  "Santa Cruz de Toled",
  "Tantarica",
  "Yonan",
  "Callayuc",
  "Choros",
  "Cujillo",
  "Cutervo",
  "La Ramada",
  "Pimpingos",
  "Querocotillo",
  "San Andres de Cutervo",
  "San Juan de Cutervo",
  "San Luis de Lucma",
  "Santo Domingo de la Capilla",
  "Socota",
  "Toribio Casanova",
  "Bambamarca",
  "Chugur",
  "Hualgayoc",
  "Bellavista",
  "Chontali",
  "Colasay",
  "Huabal",
  "Jaen",
  "Las Pirias",
  "Pomahuaca",
  "Pucara",
  "Sallique",
  "San Felipe",
  "San Jose del Alto",
  "Chirinos",
  "Huarango",
  "La Coipa",
  "Namballe",
  "San Ignacio",
  "San Jose de Lourdes",
  "Tabaconas",
  "Chancay",
  "Eduardo Villanueva",
  "Gregorio Pita",
  "Ichocan",
  "Jose Manuel Quiroz",
  "Jose Sabogal",
  "Pedro Galvez",
  "Bolivar",
  "Calquis",
  "Catilluc",
  "El Prado",
  "La Florida",
  "Llapa",
  "Nanchoc",
  "Niepos",
  "San Gregorio",
  "San Silvestre de Cochan",
  "Tongod",
  "Union Agua Blanca",
  "San Bernardino",
  "San Pablo",
  "Tumbaden",
  "Andabamba",
  "Catache",
  "Chancaybaqos",
  "La Esperanza",
  "Ninabamba",
  "Pulan",
  "Saucepampa",
  "Sexi",
  "Uticyacu",
  "Yauyucan",
  "Acomayo",
  "Acopia",
  "Acos",
  "Mosoc Llacta",
  "Pomacanchi",
  "Rondocan",
  "Sangarara",
  "Ancahuasi",
  "Cachimayo",
  "Chinchaypujio",
  "Huarocondo",
  "Limatambo",
  "Mollepata",
  "Pucyura",
  "Zurite",
  "Calca",
  "Coya",
  "Lamay",
  "Lares",
  "Pisac",
  "San Salvador",
  "Taray",
  "Yanatile",
  "Checca",
  "Kunturkanki",
  "Langui",
  "Layo",
  "Quehue",
  "Tupac Amaru",
  "Yanaoca",
  "Checacupe",
  "Combapata",
  "Marangani",
  "Pitumarca",
  "Sicuani",
  "Tinta",
  "Capacmarca",
  "Chamaca",
  "Colquemarca",
  "Livitaca",
  "Llusco",
  "Quiqota",
  "Velille",
  "Ccorca",
  "Cusco",
  "Poroy",
  "San Sebastian",
  "Santiago",
  "Saylla",
  "Wanchaq",
  "Alto Pichigua",
  "Condoroma",
  "Espinar",
  "Ocoruro",
  "Pallpata",
  "Pichigua",
  "Suyckutambo",
  "Echarate",
  "Huayopata",
  "Maranura",
  "Pichari",
  "Quellouno",
  "Quimbiri",
  "Santa Ana",
  "Santa Teresa",
  "Accha",
  "Ccapi",
  "Colcha",
  "Huanoquite",
  "Omacha",
  "Paccaritambo",
  "Paruro",
  "Pillpinto",
  "Yaurisque",
  "Caicay",
  "Challabamba",
  "Colquepata",
  "Huancarani",
  "Kosqipata",
  "Paucartambo",
  "Andahuaylillas",
  "Camanti",
  "Ccarhuayo",
  "Ccatca",
  "Cusipata",
  "Huaro",
  "Marcapata",
  "Ocongate",
  "Quiquijana",
  "Urcos",
  "Chinchero",
  "Machupicchu",
  "Maras",
  "Ollantaytambo",
  "Urubamba",
  "Yucay",
  "Caja",
  "Marcas",
  "Paucara",
  "Rosario",
  "Anchonga",
  "Callanmarca",
  "Ccochaccasa",
  "Chincho",
  "Congalla",
  "Huanca-Huanca",
  "Huayllay Grande",
  "Julcamarca",
  "Lircay",
  "San Antonio de Antaparco",
  "Santo Tomas de Pata",
  "Secclla",
  "Arma",
  "Aurahua",
  "Capillas",
  "Castrovirreyna",
  "Chupamarca",
  "Cocas",
  "Huachos",
  "Huamatambo",
  "Mollepampa",
  "Tantara",
  "Ticrapo",
  "Chinchihuasi",
  "Churcampa",
  "El Carmen",
  "Locroja",
  "Pachamarca",
  "Paucarbamba",
  "San Miguel de Mayocc",
  "San Pedro de Coris",
  "Acobambilla",
  "Acoria",
  "Ascensión",
  "Conayca",
  "Cuenca",
  "Huachocolpa",
  "Huancavelica",
  "Huando",
  "Huayllahuara",
  "Izcuchaca",
  "Laria",
  "Manta",
  "Moya",
  "Nuevo Occoro",
  "Palca",
  "Pilchaca",
  "Vilca",
  "Yauli",
  "Ayavi",
  "Cordova",
  "Huayacundo Arma",
  "Huaytara",
  "Laramarca",
  "Ocoyo",
  "Pilpichaca",
  "Querco",
  "Quito-Arma",
  "San Antonio de Cusicancha",
  "San Francisco de Sangayaico",
  "San Isidro",
  "Santiago de Chocorvos",
  "Santiago de Quirahuara",
  "Santo Domingo de Capillas",
  "Acostambo",
  "Acraquia",
  "Ahuaycha",
  "Daniel Hernandez",
  "Huaribamba",
  "Pazos",
  "Qahuimpuquio",
  "Quishuar",
  "Salcabamba",
  "Salcahuasi",
  "San Marcos de Rocchac",
  "Surcubamba",
  "Tintay Puncu",
  "Ambo",
  "Cayna",
  "Colpas",
  "Conchamarca",
  "Huacar",
  "San Francisco",
  "San Rafael",
  "Tomay Kichwa",
  "Chuquis",
  "La Union",
  "Marias",
  "Pachas",
  "Quivilla",
  "Ripan",
  "Shunqui",
  "Sillapata",
  "Yanas",
  "Canchabamba",
  "Huacaybamba",
  "Pinra",
  "Arancay",
  "Chavin de Pariarca",
  "Jacas Grande",
  "Jircan",
  "Llata",
  "Monzon",
  "Punchao",
  "Puqos",
  "Singa",
  "Tantamayo",
  "Amarilis",
  "Chinchao",
  "Churubamba",
  "Huanuco",
  "Margos",
  "Pillcomarca",
  "Quisqui",
  "San Francisco de Cayran",
  "San Pedro de Chaulan",
  "Santa Maria del Valle",
  "Yarumayo",
  "Baqos",
  "Jivia",
  "Queropalca",
  "Rondos",
  "San Francisco de Asis",
  "San Miguel de Cauri",
  "Daniel Alomias Robles",
  "Hermilio Valdizan",
  "Jose Crespo y Castillo",
  "Luyando",
  "Mariano Damaso Beraun",
  "Rupa-Rupa",
  "Cholon",
  "Huacrachuco",
  "San Buenaventura",
  "Chaglla",
  "Molino",
  "Panao",
  "Umari",
  "Codo del Pozuzo",
  "Honoria",
  "Puerto Inca",
  "Tournavista",
  "Yuyapichis",
  "Cahuac",
  "Chacabamba",
  "Chavinillo",
  "Choras",
  "Chupan",
  "Jacas Chico",
  "Obas",
  "Alto Laran",
  "Chavin",
  "Chincha Alta",
  "Chincha Baja",
  "Grocio Prado",
  "Pueblo Nuevo",
  "San Juan de Yanac",
  "San Pedro de Huacarpana",
  "Sunampe",
  "Tambo de Mora",
  "Ica",
  "La Tinguiqa",
  "Los Aquijes",
  "Ocucaje",
  "Pachacutec",
  "Parcona",
  "Salas",
  "San Jose de los Molinos",
  "Subtanjalla",
  "Tate",
  "Yauca del Rosario  1/",
  "Changuillo",
  "El Ingenio",
  "Marcona",
  "Nazca",
  "Llipata",
  "Palpa",
  "Tibillo",
  "Huancano",
  "Humay",
  "Paracas",
  "Pisco",
  "San Andres",
  "San Clemente",
  "Tupac Amaru Inca",
  "Chanchamayo",
  "Perene",
  "Pichanaqui",
  "San Luis de Shuaro",
  "San Ramon",
  "Vitoc",
  "Ahuac",
  "Chongos Bajo",
  "Chupaca",
  "Huachac",
  "Huamancaca Chico",
  "San Juan de Iscos",
  "San Juan de Jarpa",
  "Tres de Diciembre",
  "Yanacancha",
  "Andamarca",
  "Chambara",
  "Comas",
  "Heroinas Toledo",
  "Manzanares",
  "Matahuasi",
  "Mito",
  "Nueve de Julio",
  "Orcotuna",
  "San Jose de Quero",
  "Santa Rosa de Ocopa",
  "Carhuacallanga",
  "Chacapampa",
  "Chicche",
  "Chilca",
  "Chongos Alto",
  "Chupuro",
  "Cullhuas",
  "El Tambo",
  "Huacrapuquio",
  "Hualhuas",
  "Huancan",
  "Huancayo",
  "Huasicancha",
  "Huayucachi",
  "Ingenio",
  "Pilcomayo",
  "Quichuay",
  "Quilcas",
  "San Agustin",
  "San Jeronimo de Tunan",
  "Santo Domingo de Acobamba",
  "Sapallanga",
  "Saqo",
  "Sicaya",
  "Viques",
  "Acolla",
  "Apata",
  "Ataura",
  "Canchayllo",
  "Curicaca",
  "El Mantaro",
  "Huamali",
  "Huaripampa",
  "Huertas",
  "Janjaillo",
  "Jauja",
  "Julcan",
  "Leonor Ordoqez",
  "Llocllapampa",
  "Marco",
  "Masma",
  "Masma Chicche",
  "Molinos",
  "Monobamba",
  "Muqui",
  "Muquiyauyo",
  "Paca",
  "Pancan",
  "Parco",
  "Pomacancha",
  "Ricran",
  "San Lorenzo",
  "San Pedro de Chunan",
  "Sausa",
  "Sincos",
  "Tunan Marca",
  "Yauyos",
  "Carhuamayo",
  "Junin",
  "Ondores",
  "Ulcumayo",
  "Coviriali",
  "Llaylla",
  "Mazamari",
  "Pampa Hermosa",
  "Pangoa",
  "Rio Negro",
  "Rio Tambo",
  "Satipo",
  "Huaricolca",
  "Huasahuasi",
  "Palcamayo",
  "San Pedro de Cajas",
  "Tapo",
  "Tarma",
  "Chacapalpa",
  "Huay-Huay",
  "La Oroya",
  "Marcapomacocha",
  "Morococha",
  "Santa Barbara de Carhuacayan",
  "Santa Rosa de Sacco",
  "Suitucancha",
  "Ascope",
  "Casa Grande",
  "Chicama",
  "Chocope",
  "Magdalena de Cao",
  "Paijan",
  "Razuri",
  "Santiago de Cao",
  "Condormarca",
  "Longotea",
  "Uchumarca",
  "Ucuncha",
  "Chepen",
  "Pacanga",
  "Cascas",
  "Marmot",
  "Sayapullo",
  "Calamarca",
  "Carabamba",
  "Huaso",
  "Agallpampa",
  "Charat",
  "Huaranchal",
  "La Cuesta",
  "Mache",
  "Otuzco",
  "Paranday",
  "Salpo",
  "Sinsicap",
  "Usquil",
  "Guadalupe",
  "Jequetepeque",
  "Pacasmayo",
  "San Jose",
  "San Pedro de Lloc",
  "Buldibuyo",
  "Chillia",
  "Huancaspata",
  "Huaylillas",
  "Huayo",
  "Ongon",
  "Parcoy",
  "Pataz",
  "Pias",
  "Santiago de Challas",
  "Taurija",
  "Tayabamba",
  "Urpay",
  "Chugay",
  "Cochorco",
  "Curgos",
  "Huamachuco",
  "Marcabal",
  "Sanagoran",
  "Sarin",
  "Sartimbamba",
  "Angasmarca",
  "Cachicadan",
  "Mollebamba",
  "Quiruvilca",
  "Santa Cruz de Chuca",
  "Santiago de Chuco",
  "Sitabamba",
  "El Porvenir",
  "Florencia de Mora",
  "Huanchaco",
  "Laredo",
  "Moche",
  "Poroto",
  "Salaverry",
  "Simbal",
  "Trujillo",
  "Victor Larco Herrera",
  "Chao",
  "Guadalupito",
  "Viru",
  "Cayaltí",
  "Chiclayo",
  "Chongoyape",
  "Eten",
  "Eten Puerto",
  "Jose Leonardo Ortiz",
  "La Victoria",
  "Lagunas",
  "Monsefu",
  "Nueva Arica",
  "Oyotun",
  "Patapo",
  "Picsi",
  "Pimentel",
  "Pomalca",
  "Pucalá",
  "Reque",
  "Saqa",
  "Tumán",
  "Caqaris",
  "Ferreqafe",
  "Incahuasi",
  "Manuel Antonio Mesones Muro",
  "Pitipo",
  "Chochope",
  "Illimo",
  "Jayanca",
  "Lambayeque",
  "Mochumi",
  "Morrope",
  "Motupe",
  "Olmos",
  "Pacora",
  "Tucume",
  "Barranca",
  "Paramonga",
  "Pativilca",
  "Supe",
  "Supe Puerto",
  "Cajatambo",
  "Copa",
  "Gorgor",
  "Huancapon",
  "Manas",
  "Callao",
  "Carmen de la Legua Reynoso",
  "La Perla",
  "La Punta",
  "Ventanilla",
  "Asia",
  "Calango",
  "Cerro Azul",
  "Coayllo",
  "Imperial",
  "Lunahuana",
  "Mala",
  "Nuevo Imperial",
  "Pacaran",
  "Quilmana",
  "San Vicente de Cañete",
  "Santa Cruz de Flores",
  "Zuqiga",
  "Arahuay",
  "Canta",
  "Huamantanga",
  "Huaros",
  "Lachaqui",
  "Santa Rosa de Quives",
  "Atavillos Alto",
  "Atavillos Bajo",
  "Aucallama",
  "Huaral",
  "Ihuari",
  "Lampian",
  "Pacaraos",
  "San Miguel de Acos",
  "Santa Cruz de Andamarca",
  "Sumbilca",
  "Veintisiete de Noviembre",
  "Antioquia",
  "Callahuanca",
  "Carampoma",
  "Chicla",
  "Huachupampa",
  "Huanza",
  "Huarochiri",
  "Lahuaytambo",
  "Langa",
  "Laraos",
  "Mariatana",
  "Matucana",
  "Ricardo Palma",
  "San Andres de Tupicocha",
  "San Bartolome",
  "San Damian",
  "San Juan de Iris",
  "San Juan de Tantaranche",
  "San Lorenzo de Quinti",
  "San Mateo",
  "San Mateo de Otao",
  "San Pedro de Casta",
  "San Pedro de Huancayre",
  "Sangallaya",
  "Santa Cruz de Cocachacra",
  "Santa Eulalia",
  "Santiago de Anchucaya",
  "Santiago de Tuna",
  "Santo Domingo de los Olleros",
  "Surco",
  "Ambar",
  "Caleta de Carquin",
  "Checras",
  "Huacho",
  "Hualmay",
  "Huaura",
  "Paccho",
  "Santa Leonor",
  "Santa Maria",
  "Sayan",
  "Vegueta",
  "Ancon",
  "Ate",
  "Barranco",
  "Breña",
  "Carabayllo",
  "Cercado de Lima",
  "Chaclacayo",
  "Chorrillos",
  "Cieneguilla",
  "El Agustino",
  "Jesus Maria",
  "La Molina",
  "Lince",
  "Los Olivos",
  "Lurigancho",
  "Lurin",
  "Magdalena del Mar",
  "Pachacamac",
  "Pucusana",
  "Puente Piedra",
  "Punta Hermosa",
  "Punta Negra",
  "Rimac",
  "San Bartolo",
  "San Borja",
  "San Juan de Lurigancho",
  "San Juan de Miraflores",
  "San Martin de Porres",
  "Santa Anita",
  "Santa Maria del Mar",
  "Santiago de Surco",
  "Surquillo",
  "Villa El Salvador",
  "Villa Maria del Triunfo",
  "Andajes",
  "Caujul",
  "Cochamarca",
  "Navan",
  "Oyon",
  "Pachangara",
  "Alis",
  "Ayauca",
  "Ayaviri",
  "Azangaro",
  "Cacra",
  "Carania",
  "Catahuasi",
  "Chocos",
  "Colonia",
  "Hongos",
  "Huampara",
  "Huancaya",
  "Huangascar",
  "Huantan",
  "Huaqec",
  "Lincha",
  "Madean",
  "Omas",
  "Putinza",
  "Quinches",
  "Quinocay",
  "San Joaquin",
  "San Pedro de Pilas",
  "Tanta",
  "Tauripampa",
  "Tomas",
  "Tupe",
  "Viqac",
  "Vitis",
  "Balsapuerto",
  "Cahuapanas",
  "Jeberos",
  "Manseriche",
  "Morona",
  "Pastaza",
  "Teniente Cesar Lopez Rojas",
  "Yurimaguas",
  "Nauta",
  "Parinari",
  "Tigre",
  "Trompeteros",
  "Urarinas",
  "Pebas",
  "Ramon Castilla",
  "Yavari",
  "Alto Nanay",
  "Belén",
  "Fernando Lores",
  "Indiana",
  "Iquitos",
  "Las Amazonas",
  "Mazan",
  "Napo",
  "Punchana",
  "Putumayo",
  "Torres Causana",
  "Yaquerana",
  "Alto Tapiche",
  "Capelo",
  "Emilio San Martin",
  "Jenaro Herrera",
  "Maquia",
  "Puinahua",
  "Requena",
  "Saquena",
  "Soplin",
  "Tapiche",
  "Contamana",
  "Inahuaya",
  "Padre Marquez",
  "Sarayacu",
  "Vargas Guerra",
  "Fitzcarrald",
  "Huepetuhe",
  "Madre de Dios",
  "Manu",
  "Iberia",
  "Iqapari",
  "Tahuamanu",
  "Inambari",
  "Laberinto",
  "Las Piedras",
  "Tambopata",
  "Chojata",
  "Coalaque",
  "Ichuqa",
  "La Capilla",
  "Lloque",
  "Matalaque",
  "Omate",
  "Puquina",
  "Quinistaquillas",
  "Ubinas",
  "Yunga",
  "El Algarrobal",
  "Ilo",
  "Pacocha",
  "Carumas",
  "Cuchumbaya",
  "Moquegua",
  "Samegua",
  "Torata",
  "Chacayan",
  "Goyllarisquizga",
  "Paucar",
  "San Pedro de Pillao",
  "Santa Ana de Tusi",
  "Tapuc",
  "Yanahuanca",
  "Chontabamba",
  "Huancabamba",
  "Oxapampa",
  "Palcazu",
  "Pozuzo",
  "Puerto Bermudez",
  "Villa Rica",
  "Chaupimarca",
  "Huachon",
  "Huariaca",
  "Huayllay",
  "Ninacaca",
  "Pallanchacra",
  "San Fco.De Asis de Yarusyacan",
  "Simon Bolivar",
  "Ticlacayan",
  "Tinyahuarco",
  "Vicco",
  "Ayabaca",
  "Frias",
  "Jilili",
  "Montero",
  "Pacaipampa",
  "Paimas",
  "Sapillica",
  "Sicchez",
  "Suyo",
  "Canchaque",
  "El Carmen de la Frontera",
  "Huarmaca",
  "Lalaquiz",
  "San Miguel de El Faique",
  "Sondor",
  "Sondorillo",
  "Buenos Aires",
  "Chalaco",
  "Chulucanas",
  "La Matanza",
  "Morropon",
  "Salitral",
  "San Juan de Bigote",
  "Santa Catalina de Mossa",
  "Santo Domingo",
  "Yamango",
  "Amotape",
  "Arenal",
  "Colan",
  "La Huaca",
  "Paita",
  "Tamarindo",
  "Vichayal",
  "Castilla",
  "Catacaos",
  "Cura Mori",
  "El Tallan",
  "La Arena",
  "Las Lomas",
  "Piura",
  "Tambo Grande",
  "Bellavista de la Union",
  "Bernal",
  "Cristo Nos Valga",
  "Rinconada Llicuar",
  "Sechura",
  "Vice",
  "Ignacio Escudero",
  "Lancones",
  "Marcavelica",
  "Miguel Checa",
  "Querecotillo",
  "Sullana",
  "El Alto",
  "La Brea",
  "Lobitos",
  "Los Organos",
  "Mancora",
  "Pariqas",
  "Achaya",
  "Arapa",
  "Asillo",
  "Caminaca",
  "Chupa",
  "Jose Domingo Choquehuanca",
  "Muqani",
  "Potoni",
  "Saman",
  "San Anton",
  "San Juan de Salinas",
  "Santiago de Pupuja",
  "Tirapata",
  "Ajoyani",
  "Ayapata",
  "Coasa",
  "Corani",
  "Crucero",
  "Ituata",
  "Macusani",
  "Ollachea",
  "San Gaban",
  "Usicayos",
  "Desaguadero",
  "Huacullani",
  "Juli",
  "Kelluyo",
  "Pisacoma",
  "Pomata",
  "Zepita",
  "Capazo",
  "Conduriri",
  "Ilave",
  "Pilcuyo",
  "Cojata",
  "Huancane",
  "Huatasani",
  "Inchupalla",
  "Pusi",
  "Rosaspata",
  "Taraco",
  "Vilque Chico",
  "Cabanilla",
  "Calapuja",
  "Nicasio",
  "Ocuviri",
  "Paratia",
  "Vilavila",
  "Antauta",
  "Cupi",
  "Llalli",
  "Macari",
  "Nuqoa",
  "Orurillo",
  "Umachiri",
  "Conima",
  "Huayrapata",
  "Moho",
  "Tilali",
  "Acora",
  "Amantani",
  "Atuncolla",
  "Capachica",
  "Chucuito",
  "Coata",
  "Maqazo",
  "Paucarcolla",
  "Pichacani",
  "Plateria",
  "Puno",
  "Tiquillaca",
  "Vilque",
  "Ananea",
  "Pedro Vilca Apaza",
  "Putina",
  "Quilcapuncu",
  "Sina",
  "Cabanillas",
  "Caracoto",
  "Juliaca",
  "Alto Inambari",
  "Cuyocuyo",
  "Limbani",
  "Patambuco",
  "Phara",
  "Quiaca",
  "San Juan del Oro",
  "Sandia",
  "Yanahuaya",
  "Anapia",
  "Copani",
  "Cuturapi",
  "Ollaraya",
  "Tinicachi",
  "Unicachi",
  "Yunguyo",
  "Alto Biavo",
  "Bajo Biavo",
  "Huallaga",
  "Agua Blanca",
  "San Jose de Sisa",
  "San Martin",
  "Shatoja",
  "Alto Saposoa",
  "El Eslabon",
  "Piscoyacu",
  "Sacanche",
  "Saposoa",
  "Tingo de Saposoa",
  "Alonso de Alvarado",
  "Barranquita",
  "Caynarachi",
  "Cuqumbuqui",
  "Lamas",
  "Pinto Recodo",
  "Rumisapa",
  "San Roque de Cumbaza",
  "Shanao",
  "Tabalosos",
  "Zapatero",
  "Campanilla",
  "Huicungo",
  "Juanjui",
  "Pachiza",
  "Pajarillo",
  "Calzada",
  "Habana",
  "Jepelacio",
  "Moyobamba",
  "Soritor",
  "Yantalo",
  "Caspisapa",
  "Picota",
  "Pilluana",
  "Pucacaca",
  "San Hilarion",
  "Shamboyacu",
  "Tingo de Ponasa",
  "Tres Unidos",
  "Awajun",
  "Elias Soplin Vargas",
  "Nueva Cajamarca",
  "Pardo Miguel",
  "Posic",
  "Rioja",
  "San Fernando",
  "Yorongos",
  "Yuracyacu",
  "Alberto Leveau",
  "Cacatachi",
  "Chazuta",
  "Chipurana",
  "Huimbayoc",
  "Juan Guerra",
  "La Banda de Shilcayo",
  "Morales",
  "Papaplaya",
  "Sauce",
  "Shapaja",
  "Tarapoto",
  "Nuevo Progreso",
  "Polvora",
  "Shunte",
  "Tocache",
  "Uchiza",
  "Cairani",
  "Camilaca",
  "Candarave",
  "Curibaya",
  "Huanuara",
  "Quilahuani",
  "Ilabaya",
  "Ite",
  "Locumba",
  "Alto de la Alianza",
  "Calana",
  "Ciudad Nueva",
  "Cor Gregorio Albarracín",
  "Inclan",
  "Pachia",
  "Pocollay",
  "Sama",
  "Tacna",
  "Chucatamani",
  "Estique",
  "Estique-Pampa",
  "Sitajara",
  "Susapaya",
  "Tarata",
  "Tarucachi",
  "Ticaco",
  "Casitas",
  "Zorritos",
  "Corrales",
  "La Cruz",
  "Pampas de Hospital",
  "San Jacinto",
  "San Juan de la Virgen",
  "Tumbes",
  "Aguas Verdes",
  "Matapalo",
  "Papayal",
  "Zarumilla",
  "Raymondi",
  "Sepahua",
  "Tahuania",
  "Yurua",
  "Calleria",
  "Campoverde",
  "Iparia",
  "Masisea",
  "Nueva Requena",
  "Yarinacocha",
  "Curimana",
  "Irazola",
  "Padre Abad",
  "Purus",
] as const;
export const ubigeos = {
  Amazonas: {
    Bagua: ["Aramango", "Copallin", "El Parco", "Imaza", "La Peca"],
    Bongara: [
      "Chisquilla",
      "Churuja",
      "Corosha",
      "Cuispes",
      "Florida",
      "Jazan",
      "Jumbilla",
      "Recta",
      "San Carlos",
      "Shipasbamba",
      "Valera",
      "Yambrasbamba",
    ],
    Chachapoyas: [
      "Asuncion",
      "Balsas",
      "Chachapoyas",
      "Cheto",
      "Chiliquin",
      "Chuquibamba",
      "Granada",
      "Huancas",
      "La Jalca",
      "Leimebamba",
      "Levanto",
      "Magdalena",
      "Mariscal Castilla",
      "Molinopampa",
      "Montevideo",
      "Olleros",
      "Quinjalca",
      "San Francisco de Daguas",
      "San Isidro de Maino",
      "Soloco",
      "Sonche",
    ],
    Condorcanqui: ["El Cenepa", "Nieva", "Rio Santiago"],
    Luya: [
      "Camporredondo",
      "Cocabamba",
      "Colcamar",
      "Conila",
      "Inguilpata",
      "Lamud",
      "Longuita",
      "Lonya Chico",
      "Luya",
      "Luya Viejo",
      "Maria",
      "Ocalli",
      "Ocumal",
      "Pisuquia",
      "Providencia",
      "San Cristobal",
      "San Francisco del Yeso",
      "San Jeronimo",
      "San Juan de Lopecancha",
      "Santa Catalina",
      "Santo Tomas",
      "Tingo",
      "Trita",
    ],
    "Rodriguez de Mendoza": [
      "Chirimoto",
      "Cochamal",
      "Huambo",
      "Limabamba",
      "Longar",
      "Mariscal Benavides",
      "Milpuc",
      "Omia",
      "San Nicolas",
      "Santa Rosa",
      "Totora",
      "Vista Alegre",
    ],
    Utcubamba: [
      "Bagua Grande",
      "Cajaruro",
      "Cumba",
      "El Milagro",
      "Jamalca",
      "Lonya Grande",
      "Yamon",
    ],
  },
  Ancash: {
    Aija: ["Aija", "Coris", "Huacllan", "La Merced", "Succha"],
    "Antonio Raymondi": [
      "Aczo",
      "Chaccho",
      "Chingas",
      "Llamellin",
      "Mirgas",
      "San Juan de Rontoy",
    ],
    Asuncion: ["Acochaca", "Chacas"],
    Bolognesi: [
      "Abelardo Pardo Lezameta",
      "Antonio Raymondi",
      "Aquia",
      "Cajacay",
      "Canis",
      "Chiquian",
      "Colquioc",
      "Huallanca",
      "Huasta",
      "Huayllacayan",
      "La Primavera",
      "Mangas",
      "Pacllon",
      "San Miguel de Corpanqui",
      "Ticllos",
    ],
    Carhuaz: [
      "Acopampa",
      "Amashca",
      "Anta",
      "Ataquero",
      "Carhuaz",
      "Marcara",
      "Pariahuanca",
      "San Miguel de Aco",
      "Shilla",
      "Tinco",
      "Yungar",
    ],
    "Carlos Fermin Fitzcarrald": ["San Luis", "San Nicolas", "Yauya"],
    Casma: ["Buena Vista Alta", "Casma", "Comandante Noel", "Yautan"],
    Corongo: [
      "Aco",
      "Bambas",
      "Corongo",
      "Cusca",
      "La Pampa",
      "Yanac",
      "Yupan",
    ],
    Huaraz: [
      "Cochabamba",
      "Colcabamba",
      "Huanchay",
      "Huaraz",
      "Independencia",
      "Jangas",
      "La Libertad",
      "Olleros",
      "Pampas",
      "Pariacoto",
      "Pira",
      "Tarica",
    ],
    Huari: [
      "Anra",
      "Cajay",
      "Chavin de Huantar",
      "Huacachi",
      "Huacchis",
      "Huachis",
      "Huantar",
      "Huari",
      "Masin",
      "Paucas",
      "Ponto",
      "Rahuapampa",
      "Rapayan",
      "San Marcos",
      "San Pedro de Chana",
      "Uco",
    ],
    Huarmey: ["Cochapeti", "Culebras", "Huarmey", "Huayan", "Malvas"],
    Huaylas: [
      "Caraz",
      "Huallanca",
      "Huata",
      "Huaylas",
      "Mato",
      "Pamparomas",
      "Pueblo Libre",
      "Santa Cruz",
      "Santo Toribio",
      "Yuracmarca",
    ],
    "Mariscal Luzuriaga": [
      "Casca",
      "Eleazar Guzman Barron",
      "Fidel Olivas Escudero",
      "Llama",
      "Llumpa",
      "Lucma",
      "Musga",
      "Piscobamba",
    ],
    Ocros: [
      "Acas",
      "Cajamarquilla",
      "Carhuapampa",
      "Cochas",
      "Congas",
      "Llipa",
      "Ocros",
      "San Cristobal de Rajan",
      "San Pedro",
      "Santiago de Chilcas",
    ],
    Pallasca: [
      "Bolognesi",
      "Cabana",
      "Conchucos",
      "Huacaschuque",
      "Huandoval",
      "Lacabamba",
      "Llapo",
      "Pallasca",
      "Pampas",
      "Santa Rosa",
      "Tauca",
    ],
    Pomabamba: ["Huayllan", "Parobamba", "Pomabamba", "Quinuabamba"],
    Recuay: [
      "Catac",
      "Cotaparaco",
      "Huayllapampa",
      "Llacllin",
      "Marca",
      "Pampas Chico",
      "Pararin",
      "Recuay",
      "Tapacocha",
      "Ticapampa",
    ],
    Santa: [
      "Caceres del Peru",
      "Chimbote",
      "Coishco",
      "Macate",
      "Moro",
      "Nepeqa",
      "Nuevo Chimbote",
      "Samanco",
      "Santa",
    ],
    Sihuas: [
      "Acobamba",
      "Alfonso Ugarte",
      "Cashapampa",
      "Chingalpo",
      "Huayllabamba",
      "Quiches",
      "Ragash",
      "San Juan",
      "Sicsibamba",
      "Sihuas",
    ],
    Yungay: [
      "Cascapara",
      "Mancos",
      "Matacoto",
      "Quillo",
      "Ranrahirca",
      "Shupluy",
      "Yanama",
      "Yungay",
    ],
  },
  Apurimac: {
    Abancay: [
      "Abancay",
      "Chacoche",
      "Circa",
      "Curahuasi",
      "Huanipaca",
      "Lambrama",
      "Pichirhua",
      "San Pedro de Cachora",
      "Tamburco",
    ],
    Andahuaylas: [
      "Andahuaylas",
      "Andarapa",
      "Chiara",
      "Huancarama",
      "Huancaray",
      "Huayana",
      "Kaquiabamba",
      "Kishuara",
      "Pacobamba",
      "Pacucha",
      "Pampachiri",
      "Pomacocha",
      "San Antonio de Cachi",
      "San Jeronimo",
      "San Miguel de Chaccrampa",
      "Santa Maria de Chicmo",
      "Talavera",
      "Tumay Huaraca",
      "Turpo",
    ],
    Antabamba: [
      "Antabamba",
      "El Oro",
      "Huaquirca",
      "Juan Espinoza Medrano",
      "Oropesa",
      "Pachaconas",
      "Sabaino",
    ],
    Aymaraes: [
      "Capaya",
      "Caraybamba",
      "Chalhuanca",
      "Chapimarca",
      "Colcabamba",
      "Cotaruse",
      "Huayllo",
      "Justo Apu Sahuaraura",
      "Lucre",
      "Pocohuanca",
      "San Juan de Chacqa",
      "Saqayca",
      "Soraya",
      "Tapairihua",
      "Tintay",
      "Toraya",
      "Yanaca",
    ],
    Chincheros: [
      "Anco-Huallo",
      "Chincheros",
      "Cocharcas",
      "Huaccana",
      "Ocobamba",
      "Ongoy",
      "Ranracancha",
      "Uranmarca",
    ],
    Cotabambas: [
      "Challhuahuacho",
      "Cotabambas",
      "Coyllurqui",
      "Haquira",
      "Mara",
      "Tambobamba",
    ],
    Grau: [
      "Chuquibambilla",
      "Curasco",
      "Curpahuasi",
      "Gamarra",
      "Huayllati",
      "Mamara",
      "Micaela Bastidas",
      "Pataypampa",
      "Progreso",
      "San Antonio",
      "Santa Rosa",
      "Turpay",
      "Vilcabamba",
      "Virundo",
    ],
  },
  Arequipa: {
    Arequipa: [
      "Alto Selva Alegre",
      "Arequipa",
      "Cayma",
      "Cerro Colorado",
      "Characato",
      "Chiguata",
      "Jacobo Hunter",
      "Jose Luis Bustamante y Rivero",
      "La Joya",
      "Mariano Melgar",
      "Miraflores",
      "Mollebaya",
      "Paucarpata",
      "Pocsi",
      "Polobaya",
      "Quequeqa",
      "Sabandia",
      "Sachaca",
      "San Juan de Siguas",
      "San Juan de Tarucani",
      "Santa Isabel de Siguas",
      "Santa Rita de Siguas",
      "Socabaya",
      "Tiabaya",
      "Uchumayo",
      "Vitor",
      "Yanahuara",
      "Yarabamba",
      "Yura",
    ],
    Camana: [
      "Camana",
      "Jose Maria Quimper",
      "Mariano Nicolas Valcarcel",
      "Mariscal Caceres",
      "Nicolas de Pierola",
      "Ocoqa",
      "Quilca",
      "Samuel Pastor",
    ],
    Caraveli: [
      "Acari",
      "Atico",
      "Atiquipa",
      "Bella Union",
      "Cahuacho",
      "Caraveli",
      "Chala",
      "Chaparra",
      "Huanuhuanu",
      "Jaqui",
      "Lomas",
      "Quicacha",
      "Yauca",
    ],
    Castilla: [
      "Andagua",
      "Aplao",
      "Ayo",
      "Chachas",
      "Chilcaymarca",
      "Choco",
      "Huancarqui",
      "Machaguay",
      "Majes",
      "Orcopampa",
      "Pampacolca",
      "Tipan",
      "Uqon",
      "Uraca",
      "Viraco",
      "Yanque",
    ],
    Caylloma: [
      "Achoma",
      "Cabanaconde",
      "Callalli",
      "Caylloma",
      "Chivay",
      "Coporaque",
      "Huambo",
      "Huanca",
      "Ichupampa",
      "Lari",
      "Lluta",
      "Maca",
      "Madrigal",
      "Majes",
      "San Antonio de Chuca",
      "Sibayo",
      "Tapay",
      "Tisco",
      "Tuti",
      "Yanque",
    ],
    Condesuyos: [
      "Andaray",
      "Cayarani",
      "Chichas",
      "Chuquibamba",
      "Iray",
      "Rio Grande",
      "Salamanca",
      "Yanaquihua",
    ],
    Islay: [
      "Cocachacra",
      "Dean Valdivia",
      "Islay",
      "Mejia",
      "Mollendo",
      "Punta de Bombon",
    ],
    "La Union": [
      "Alca",
      "Charcana",
      "Cotahuasi",
      "Huaynacotas",
      "Pampamarca",
      "Puyca",
      "Quechualla",
      "Sayla",
      "Tauria",
      "Tomepampa",
      "Toro",
    ],
  },
  Ayacucho: {
    Cangallo: [
      "Cangallo",
      "Chuschi",
      "Los Morochucos",
      "Maria Parado de Bellido",
      "Paras",
      "Totos",
    ],
    Huamanga: [
      "Acocro",
      "Acos Vinchos",
      "Ayacucho",
      "Carmen Alto",
      "Chiara",
      "Jesús Nazareno",
      "Ocros",
      "Pacaycasa",
      "Quinua",
      "San Jose de Ticllas",
      "San Juan Bautista",
      "Santiago de Pischa",
      "Socos",
      "Tambillo",
      "Vinchos",
    ],
    "Huanca Sancos": [
      "Carapo",
      "Sacsamarca",
      "Sancos",
      "Santiago de Lucanamarca",
    ],
    Huanta: [
      "Ayahuanco",
      "Huamanguilla",
      "Huanta",
      "Iguain",
      "Llochegua",
      "Luricocha",
      "Santillana",
      "Sivia",
    ],
    "La Mar": [
      "Anco",
      "Ayna",
      "Chilcas",
      "Chungui",
      "Luis Carranza",
      "San Miguel",
      "Santa Rosa",
      "Tambo",
    ],
    Lucanas: [
      "Aucara",
      "Cabana",
      "Carmen Salcedo",
      "Chaviqa",
      "Chipao",
      "Huac-Huas",
      "Laramate",
      "Leoncio Prado",
      "Llauta",
      "Lucanas",
      "Ocaqa",
      "Otoca",
      "Puquio",
      "Saisa",
      "San Cristobal",
      "San Juan",
      "San Pedro",
      "San Pedro de Palco",
      "Sancos",
      "Santa Ana de Huaycahuacho",
      "Santa Lucia",
    ],
    Parinacochas: [
      "Chumpi",
      "Coracora",
      "Coronel Castaqeda",
      "Pacapausa",
      "Pullo",
      "Puyusca",
      "San Francisco de Ravacayco",
      "Upahuacho",
    ],
    "Paucar del Sara Sara": [
      "Colta",
      "Corculla",
      "Lampa",
      "Marcabamba",
      "Oyolo",
      "Pararca",
      "Pausa",
      "San Javier de Alpabamba",
      "San Jose de Ushua",
      "Sara Sara",
    ],
    Sucre: [
      "Belen",
      "Chalcos",
      "Chilcayoc",
      "Huacaqa",
      "Morcolla",
      "Paico",
      "Querobamba",
      "San Pedro de Larcay",
      "San Salvador de Quije",
      "Santiago de Paucaray",
      "Soras",
    ],
    "Victor Fajardo": [
      "Alcamenca",
      "Apongo",
      "Asquipata",
      "Canaria",
      "Cayara",
      "Colca",
      "Huamanquiquia",
      "Huancapi",
      "Huancaraylla",
      "Huaya",
      "Sarhua",
      "Vilcanchos",
    ],
    "Vilcas Huaman": [
      "Accomarca",
      "Carhuanca",
      "Concepcion",
      "Huambalpa",
      "Independencia",
      "Saurama",
      "Vilcas Huaman",
      "Vischongo",
    ],
  },
  Cajamarca: {
    Cajabamba: ["Cachachi", "Cajabamba", "Condebamba", "Sitacocha"],
    Cajamarca: [
      "Asuncion",
      "Cajamarca",
      "Chetilla",
      "Cospan",
      "Encaqada",
      "Jesus",
      "Llacanora",
      "Los Baqos del Inca",
      "Magdalena",
      "Matara",
      "Namora",
      "San Juan",
    ],
    Celendin: [
      "Celendin",
      "Chumuch",
      "Cortegana",
      "Huasmin",
      "Jorge Chavez",
      "Jose Galvez",
      "La Libertad de Pallan",
      "Miguel Iglesias",
      "Oxamarca",
      "Sorochuco",
      "Sucre",
      "Utco",
    ],
    Chota: [
      "Anguia",
      "Chadin",
      "Chalamarca",
      "Chiguirip",
      "Chimban",
      "Choropampa",
      "Chota",
      "Cochabamba",
      "Conchan",
      "Huambos",
      "Lajas",
      "Llama",
      "Miracosta",
      "Paccha",
      "Pion",
      "Querocoto",
      "San Juan de Licupis",
      "Tacabamba",
      "Tocmoche",
    ],
    Contumaza: [
      "Chilete",
      "Contumaza",
      "Cupisnique",
      "Guzmango",
      "San Benito",
      "Santa Cruz de Toled",
      "Tantarica",
      "Yonan",
    ],
    Cutervo: [
      "Callayuc",
      "Choros",
      "Cujillo",
      "Cutervo",
      "La Ramada",
      "Pimpingos",
      "Querocotillo",
      "San Andres de Cutervo",
      "San Juan de Cutervo",
      "San Luis de Lucma",
      "Santa Cruz",
      "Santo Domingo de la Capilla",
      "Santo Tomas",
      "Socota",
      "Toribio Casanova",
    ],
    Hualgayoc: ["Bambamarca", "Chugur", "Hualgayoc"],
    Jaen: [
      "Bellavista",
      "Chontali",
      "Colasay",
      "Huabal",
      "Jaen",
      "Las Pirias",
      "Pomahuaca",
      "Pucara",
      "Sallique",
      "San Felipe",
      "San Jose del Alto",
      "Santa Rosa",
    ],
    "San Ignacio": [
      "Chirinos",
      "Huarango",
      "La Coipa",
      "Namballe",
      "San Ignacio",
      "San Jose de Lourdes",
      "Tabaconas",
    ],
    "San Marcos": [
      "Chancay",
      "Eduardo Villanueva",
      "Gregorio Pita",
      "Ichocan",
      "Jose Manuel Quiroz",
      "Jose Sabogal",
      "Pedro Galvez",
    ],
    "San Miguel": [
      "Bolivar",
      "Calquis",
      "Catilluc",
      "El Prado",
      "La Florida",
      "Llapa",
      "Nanchoc",
      "Niepos",
      "San Gregorio",
      "San Miguel",
      "San Silvestre de Cochan",
      "Tongod",
      "Union Agua Blanca",
    ],
    "San Pablo": ["San Bernardino", "San Luis", "San Pablo", "Tumbaden"],
    "Santa Cruz": [
      "Andabamba",
      "Catache",
      "Chancaybaqos",
      "La Esperanza",
      "Ninabamba",
      "Pulan",
      "Santa Cruz",
      "Saucepampa",
      "Sexi",
      "Uticyacu",
      "Yauyucan",
    ],
  },
  Cusco: {
    Acomayo: [
      "Acomayo",
      "Acopia",
      "Acos",
      "Mosoc Llacta",
      "Pomacanchi",
      "Rondocan",
      "Sangarara",
    ],
    Anta: [
      "Ancahuasi",
      "Anta",
      "Cachimayo",
      "Chinchaypujio",
      "Huarocondo",
      "Limatambo",
      "Mollepata",
      "Pucyura",
      "Zurite",
    ],
    Calca: [
      "Calca",
      "Coya",
      "Lamay",
      "Lares",
      "Pisac",
      "San Salvador",
      "Taray",
      "Yanatile",
    ],
    Canas: [
      "Checca",
      "Kunturkanki",
      "Langui",
      "Layo",
      "Pampamarca",
      "Quehue",
      "Tupac Amaru",
      "Yanaoca",
    ],
    Canchis: [
      "Checacupe",
      "Combapata",
      "Marangani",
      "Pitumarca",
      "San Pablo",
      "San Pedro",
      "Sicuani",
      "Tinta",
    ],
    Chumbivilcas: [
      "Capacmarca",
      "Chamaca",
      "Colquemarca",
      "Livitaca",
      "Llusco",
      "Quiqota",
      "Santo Tomas",
      "Velille",
    ],
    Cusco: [
      "Ccorca",
      "Cusco",
      "Poroy",
      "San Jeronimo",
      "San Sebastian",
      "Santiago",
      "Saylla",
      "Wanchaq",
    ],
    Espinar: [
      "Alto Pichigua",
      "Condoroma",
      "Coporaque",
      "Espinar",
      "Ocoruro",
      "Pallpata",
      "Pichigua",
      "Suyckutambo",
    ],
    "La Convencion": [
      "Echarate",
      "Huayopata",
      "Maranura",
      "Ocobamba",
      "Pichari",
      "Quellouno",
      "Quimbiri",
      "Santa Ana",
      "Santa Teresa",
      "Vilcabamba",
    ],
    Paruro: [
      "Accha",
      "Ccapi",
      "Colcha",
      "Huanoquite",
      "Omacha",
      "Paccaritambo",
      "Paruro",
      "Pillpinto",
      "Yaurisque",
    ],
    Paucartambo: [
      "Caicay",
      "Challabamba",
      "Colquepata",
      "Huancarani",
      "Kosqipata",
      "Paucartambo",
    ],
    Quispicanchi: [
      "Andahuaylillas",
      "Camanti",
      "Ccarhuayo",
      "Ccatca",
      "Cusipata",
      "Huaro",
      "Lucre",
      "Marcapata",
      "Ocongate",
      "Oropesa",
      "Quiquijana",
      "Urcos",
    ],
    Urubamba: [
      "Chinchero",
      "Huayllabamba",
      "Machupicchu",
      "Maras",
      "Ollantaytambo",
      "Urubamba",
      "Yucay",
    ],
  },
  Huancavelica: {
    Acobamba: [
      "Acobamba",
      "Andabamba",
      "Anta",
      "Caja",
      "Marcas",
      "Paucara",
      "Pomacocha",
      "Rosario",
    ],
    Angaraes: [
      "Anchonga",
      "Callanmarca",
      "Ccochaccasa",
      "Chincho",
      "Congalla",
      "Huanca-Huanca",
      "Huayllay Grande",
      "Julcamarca",
      "Lircay",
      "San Antonio de Antaparco",
      "Santo Tomas de Pata",
      "Secclla",
    ],
    Castrovirreyna: [
      "Arma",
      "Aurahua",
      "Capillas",
      "Castrovirreyna",
      "Chupamarca",
      "Cocas",
      "Huachos",
      "Huamatambo",
      "Mollepampa",
      "San Juan",
      "Santa Ana",
      "Tantara",
      "Ticrapo",
    ],
    Churcampa: [
      "Anco",
      "Chinchihuasi",
      "Churcampa",
      "El Carmen",
      "La Merced",
      "Locroja",
      "Pachamarca",
      "Paucarbamba",
      "San Miguel de Mayocc",
      "San Pedro de Coris",
    ],
    Huancavelica: [
      "Acobambilla",
      "Acoria",
      "Ascensión",
      "Conayca",
      "Cuenca",
      "Huachocolpa",
      "Huancavelica",
      "Huando",
      "Huayllahuara",
      "Izcuchaca",
      "Laria",
      "Manta",
      "Mariscal Caceres",
      "Moya",
      "Nuevo Occoro",
      "Palca",
      "Pilchaca",
      "Vilca",
      "Yauli",
    ],
    Huaytara: [
      "Ayavi",
      "Cordova",
      "Huayacundo Arma",
      "Huaytara",
      "Laramarca",
      "Ocoyo",
      "Pilpichaca",
      "Querco",
      "Quito-Arma",
      "San Antonio de Cusicancha",
      "San Francisco de Sangayaico",
      "San Isidro",
      "Santiago de Chocorvos",
      "Santiago de Quirahuara",
      "Santo Domingo de Capillas",
      "Tambo",
    ],
    Tayacaja: [
      "Acostambo",
      "Acraquia",
      "Ahuaycha",
      "Colcabamba",
      "Daniel Hernandez",
      "Huachocolpa",
      "Huando",
      "Huaribamba",
      "Pachamarca",
      "Pampas",
      "Pazos",
      "Qahuimpuquio",
      "Quishuar",
      "Salcabamba",
      "Salcahuasi",
      "San Marcos de Rocchac",
      "Surcubamba",
      "Tintay Puncu",
    ],
  },
  Huanuco: {
    Ambo: [
      "Ambo",
      "Cayna",
      "Colpas",
      "Conchamarca",
      "Huacar",
      "San Francisco",
      "San Rafael",
      "Tomay Kichwa",
    ],
    "Dos de Mayo": [
      "Chuquis",
      "La Union",
      "Marias",
      "Pachas",
      "Quivilla",
      "Ripan",
      "Shunqui",
      "Sillapata",
      "Yanas",
    ],
    Huacaybamba: ["Canchabamba", "Cochabamba", "Huacaybamba", "Pinra"],
    Huamalies: [
      "Arancay",
      "Chavin de Pariarca",
      "Jacas Grande",
      "Jircan",
      "Llata",
      "Miraflores",
      "Monzon",
      "Punchao",
      "Puqos",
      "Singa",
      "Tantamayo",
    ],
    Huanuco: [
      "Amarilis",
      "Chinchao",
      "Churubamba",
      "Huanuco",
      "Margos",
      "Pillcomarca",
      "Quisqui",
      "San Francisco de Cayran",
      "San Pedro de Chaulan",
      "Santa Maria del Valle",
      "Yarumayo",
    ],
    Lauricocha: [
      "Baqos",
      "Jesus",
      "Jivia",
      "Queropalca",
      "Rondos",
      "San Francisco de Asis",
      "San Miguel de Cauri",
    ],
    "Leoncio Prado": [
      "Daniel Alomias Robles",
      "Hermilio Valdizan",
      "Jose Crespo y Castillo",
      "Luyando",
      "Mariano Damaso Beraun",
      "Rupa-Rupa",
    ],
    Maraqon: ["Cholon", "Huacrachuco", "San Buenaventura"],
    Pachitea: ["Chaglla", "Molino", "Panao", "Umari"],
    "Puerto Inca": [
      "Codo del Pozuzo",
      "Honoria",
      "Puerto Inca",
      "Tournavista",
      "Yuyapichis",
    ],
    Yarowilca: [
      "Cahuac",
      "Chacabamba",
      "Chavinillo",
      "Choras",
      "Chupan",
      "Jacas Chico",
      "Obas",
      "Pampamarca",
    ],
  },
  Ica: {
    Chincha: [
      "Alto Laran",
      "Chavin",
      "Chincha Alta",
      "Chincha Baja",
      "El Carmen",
      "Grocio Prado",
      "Pueblo Nuevo",
      "San Juan de Yanac",
      "San Pedro de Huacarpana",
      "Sunampe",
      "Tambo de Mora",
    ],
    Ica: [
      "Ica",
      "La Tinguiqa",
      "Los Aquijes",
      "Ocucaje",
      "Pachacutec",
      "Parcona",
      "Pueblo Nuevo",
      "Salas",
      "San Jose de los Molinos",
      "San Juan Bautista",
      "Santiago",
      "Subtanjalla",
      "Tate",
      "Yauca del Rosario  1/",
    ],
    Nazca: ["Changuillo", "El Ingenio", "Marcona", "Nazca", "Vista Alegre"],
    Palpa: ["Llipata", "Palpa", "Rio Grande", "Santa Cruz", "Tibillo"],
    Pisco: [
      "Huancano",
      "Humay",
      "Independencia",
      "Paracas",
      "Pisco",
      "San Andres",
      "San Clemente",
      "Tupac Amaru Inca",
    ],
  },
  Junin: {
    Chanchamayo: [
      "Chanchamayo",
      "Perene",
      "Pichanaqui",
      "San Luis de Shuaro",
      "San Ramon",
      "Vitoc",
    ],
    Chupaca: [
      "Ahuac",
      "Chongos Bajo",
      "Chupaca",
      "Huachac",
      "Huamancaca Chico",
      "San Juan de Iscos",
      "San Juan de Jarpa",
      "Tres de Diciembre",
      "Yanacancha",
    ],
    Concepcion: [
      "Aco",
      "Andamarca",
      "Chambara",
      "Cochas",
      "Comas",
      "Concepcion",
      "Heroinas Toledo",
      "Manzanares",
      "Mariscal Castilla",
      "Matahuasi",
      "Mito",
      "Nueve de Julio",
      "Orcotuna",
      "San Jose de Quero",
      "Santa Rosa de Ocopa",
    ],
    Huancayo: [
      "Carhuacallanga",
      "Chacapampa",
      "Chicche",
      "Chilca",
      "Chongos Alto",
      "Chupuro",
      "Colca",
      "Cullhuas",
      "El Tambo",
      "Huacrapuquio",
      "Hualhuas",
      "Huancan",
      "Huancayo",
      "Huasicancha",
      "Huayucachi",
      "Ingenio",
      "Pariahuanca",
      "Pilcomayo",
      "Pucara",
      "Quichuay",
      "Quilcas",
      "San Agustin",
      "San Jeronimo de Tunan",
      "Santo Domingo de Acobamba",
      "Sapallanga",
      "Saqo",
      "Sicaya",
      "Viques",
    ],
    Jauja: [
      "Acolla",
      "Apata",
      "Ataura",
      "Canchayllo",
      "Curicaca",
      "El Mantaro",
      "Huamali",
      "Huaripampa",
      "Huertas",
      "Janjaillo",
      "Jauja",
      "Julcan",
      "Leonor Ordoqez",
      "Llocllapampa",
      "Marco",
      "Masma",
      "Masma Chicche",
      "Molinos",
      "Monobamba",
      "Muqui",
      "Muquiyauyo",
      "Paca",
      "Paccha",
      "Pancan",
      "Parco",
      "Pomacancha",
      "Ricran",
      "San Lorenzo",
      "San Pedro de Chunan",
      "Sausa",
      "Sincos",
      "Tunan Marca",
      "Yauli",
      "Yauyos",
    ],
    Junin: ["Carhuamayo", "Junin", "Ondores", "Ulcumayo"],
    Satipo: [
      "Coviriali",
      "Llaylla",
      "Mazamari",
      "Pampa Hermosa",
      "Pangoa",
      "Rio Negro",
      "Rio Tambo",
      "Satipo",
    ],
    Tarma: [
      "Acobamba",
      "Huaricolca",
      "Huasahuasi",
      "La Union",
      "Palca",
      "Palcamayo",
      "San Pedro de Cajas",
      "Tapo",
      "Tarma",
    ],
    Yauli: [
      "Chacapalpa",
      "Huay-Huay",
      "La Oroya",
      "Marcapomacocha",
      "Morococha",
      "Paccha",
      "Santa Barbara de Carhuacayan",
      "Santa Rosa de Sacco",
      "Suitucancha",
      "Yauli",
    ],
  },
  "La Libertad": {
    Ascope: [
      "Ascope",
      "Casa Grande",
      "Chicama",
      "Chocope",
      "Magdalena de Cao",
      "Paijan",
      "Razuri",
      "Santiago de Cao",
    ],
    Bolivar: [
      "Bambamarca",
      "Bolivar",
      "Condormarca",
      "Longotea",
      "Uchumarca",
      "Ucuncha",
    ],
    Chepen: ["Chepen", "Pacanga", "Pueblo Nuevo"],
    "Gran Chimu": ["Cascas", "Lucma", "Marmot", "Sayapullo"],
    Julcan: ["Calamarca", "Carabamba", "Huaso", "Julcan"],
    Otuzco: [
      "Agallpampa",
      "Charat",
      "Huaranchal",
      "La Cuesta",
      "Mache",
      "Otuzco",
      "Paranday",
      "Salpo",
      "Sinsicap",
      "Usquil",
    ],
    Pacasmayo: [
      "Guadalupe",
      "Jequetepeque",
      "Pacasmayo",
      "San Jose",
      "San Pedro de Lloc",
    ],
    Pataz: [
      "Buldibuyo",
      "Chillia",
      "Huancaspata",
      "Huaylillas",
      "Huayo",
      "Ongon",
      "Parcoy",
      "Pataz",
      "Pias",
      "Santiago de Challas",
      "Taurija",
      "Tayabamba",
      "Urpay",
    ],
    "Sanchez Carrion": [
      "Chugay",
      "Cochorco",
      "Curgos",
      "Huamachuco",
      "Marcabal",
      "Sanagoran",
      "Sarin",
      "Sartimbamba",
    ],
    "Santiago de Chuco": [
      "Angasmarca",
      "Cachicadan",
      "Mollebamba",
      "Mollepata",
      "Quiruvilca",
      "Santa Cruz de Chuca",
      "Santiago de Chuco",
      "Sitabamba",
    ],
    Trujillo: [
      "El Porvenir",
      "Florencia de Mora",
      "Huanchaco",
      "La Esperanza",
      "Laredo",
      "Moche",
      "Poroto",
      "Salaverry",
      "Simbal",
      "Trujillo",
      "Victor Larco Herrera",
    ],
    Viru: ["Chao", "Guadalupito", "Viru"],
  },
  Lambayeque: {
    Chiclayo: [
      "Cayaltí",
      "Chiclayo",
      "Chongoyape",
      "Eten",
      "Eten Puerto",
      "Jose Leonardo Ortiz",
      "La Victoria",
      "Lagunas",
      "Monsefu",
      "Nueva Arica",
      "Oyotun",
      "Patapo",
      "Picsi",
      "Pimentel",
      "Pomalca",
      "Pucalá",
      "Reque",
      "Santa Rosa",
      "Saqa",
      "Tumán",
    ],
    Ferreqafe: [
      "Caqaris",
      "Ferreqafe",
      "Incahuasi",
      "Manuel Antonio Mesones Muro",
      "Pitipo",
      "Pueblo Nuevo",
    ],
    Lambayeque: [
      "Chochope",
      "Illimo",
      "Jayanca",
      "Lambayeque",
      "Mochumi",
      "Morrope",
      "Motupe",
      "Olmos",
      "Pacora",
      "Salas",
      "San Jose",
      "Tucume",
    ],
  },
  Lima: {
    Barranca: ["Barranca", "Paramonga", "Pativilca", "Supe", "Supe Puerto"],
    Cajatambo: ["Cajatambo", "Copa", "Gorgor", "Huancapon", "Manas"],
    Callao: [
      "Bellavista",
      "Callao",
      "Carmen de la Legua Reynoso",
      "La Perla",
      "La Punta",
      "Ventanilla",
    ],
    Cañete: [
      "Asia",
      "Calango",
      "Cerro Azul",
      "Chilca",
      "Coayllo",
      "Imperial",
      "Lunahuana",
      "Mala",
      "Nuevo Imperial",
      "Pacaran",
      "Quilmana",
      "San Antonio",
      "San Luis",
      "San Vicente de Cañete",
      "Santa Cruz de Flores",
      "Zuqiga",
    ],
    Canta: [
      "Arahuay",
      "Canta",
      "Huamantanga",
      "Huaros",
      "Lachaqui",
      "San Buenaventura",
      "Santa Rosa de Quives",
    ],
    Huaral: [
      "Atavillos Alto",
      "Atavillos Bajo",
      "Aucallama",
      "Chancay",
      "Huaral",
      "Ihuari",
      "Lampian",
      "Pacaraos",
      "San Miguel de Acos",
      "Santa Cruz de Andamarca",
      "Sumbilca",
      "Veintisiete de Noviembre",
    ],
    Huarochiri: [
      "Antioquia",
      "Callahuanca",
      "Carampoma",
      "Chicla",
      "Cuenca",
      "Huachupampa",
      "Huanza",
      "Huarochiri",
      "Lahuaytambo",
      "Langa",
      "Laraos",
      "Mariatana",
      "Matucana",
      "Ricardo Palma",
      "San Andres de Tupicocha",
      "San Antonio",
      "San Bartolome",
      "San Damian",
      "San Juan de Iris",
      "San Juan de Tantaranche",
      "San Lorenzo de Quinti",
      "San Mateo",
      "San Mateo de Otao",
      "San Pedro de Casta",
      "San Pedro de Huancayre",
      "Sangallaya",
      "Santa Cruz de Cocachacra",
      "Santa Eulalia",
      "Santiago de Anchucaya",
      "Santiago de Tuna",
      "Santo Domingo de los Olleros",
      "Surco",
    ],
    Huaura: [
      "Ambar",
      "Caleta de Carquin",
      "Checras",
      "Huacho",
      "Hualmay",
      "Huaura",
      "Leoncio Prado",
      "Paccho",
      "Santa Leonor",
      "Santa Maria",
      "Sayan",
      "Vegueta",
    ],
    Lima: [
      "Ancon",
      "Ate",
      "Barranco",
      "Breña",
      "Carabayllo",
      "Cercado de Lima",
      "Chaclacayo",
      "Chorrillos",
      "Cieneguilla",
      "Comas",
      "El Agustino",
      "Independencia",
      "Jesus Maria",
      "La Molina",
      "La Victoria",
      "Lince",
      "Los Olivos",
      "Lurigancho",
      "Lurin",
      "Magdalena del Mar",
      "Miraflores",
      "Pachacamac",
      "Pucusana",
      "Pueblo Libre",
      "Puente Piedra",
      "Punta Hermosa",
      "Punta Negra",
      "Rimac",
      "San Bartolo",
      "San Borja",
      "San Isidro",
      "San Juan de Lurigancho",
      "San Juan de Miraflores",
      "San Luis",
      "San Martin de Porres",
      "San Miguel",
      "Santa Anita",
      "Santa Maria del Mar",
      "Santa Rosa",
      "Santiago de Surco",
      "Surquillo",
      "Villa El Salvador",
      "Villa Maria del Triunfo",
    ],
    Oyon: ["Andajes", "Caujul", "Cochamarca", "Navan", "Oyon", "Pachangara"],
    Yauyos: [
      "Alis",
      "Ayauca",
      "Ayaviri",
      "Azangaro",
      "Cacra",
      "Carania",
      "Catahuasi",
      "Chocos",
      "Cochas",
      "Colonia",
      "Hongos",
      "Huampara",
      "Huancaya",
      "Huangascar",
      "Huantan",
      "Huaqec",
      "Laraos",
      "Lincha",
      "Madean",
      "Miraflores",
      "Omas",
      "Putinza",
      "Quinches",
      "Quinocay",
      "San Joaquin",
      "San Pedro de Pilas",
      "Tanta",
      "Tauripampa",
      "Tomas",
      "Tupe",
      "Viqac",
      "Vitis",
      "Yauyos",
    ],
  },
  Loreto: {
    "Alto Amazonas": [
      "Balsapuerto",
      "Barranca",
      "Cahuapanas",
      "Jeberos",
      "Lagunas",
      "Manseriche",
      "Morona",
      "Pastaza",
      "Santa Cruz",
      "Teniente Cesar Lopez Rojas",
      "Yurimaguas",
    ],
    Loreto: ["Nauta", "Parinari", "Tigre", "Trompeteros", "Urarinas"],
    "Mariscal Ramon Castilla": [
      "Pebas",
      "Ramon Castilla",
      "San Pablo",
      "Yavari",
    ],
    Maynas: [
      "Alto Nanay",
      "Belén",
      "Fernando Lores",
      "Indiana",
      "Iquitos",
      "Las Amazonas",
      "Mazan",
      "Napo",
      "Punchana",
      "Putumayo",
      "San Juan Bautista",
      "Torres Causana",
      "Yaquerana",
    ],
    Requena: [
      "Alto Tapiche",
      "Capelo",
      "Emilio San Martin",
      "Jenaro Herrera",
      "Maquia",
      "Puinahua",
      "Requena",
      "Saquena",
      "Soplin",
      "Tapiche",
      "Yaquerana",
    ],
    Ucayali: [
      "Contamana",
      "Inahuaya",
      "Padre Marquez",
      "Pampa Hermosa",
      "Sarayacu",
      "Vargas Guerra",
    ],
  },
  "Madre de Dios": {
    Manu: ["Fitzcarrald", "Huepetuhe", "Madre de Dios", "Manu"],
    Tahuamanu: ["Iberia", "Iqapari", "Tahuamanu"],
    Tambopata: ["Inambari", "Laberinto", "Las Piedras", "Tambopata"],
  },
  Moquegua: {
    "General Sanchez Cerro": [
      "Chojata",
      "Coalaque",
      "Ichuqa",
      "La Capilla",
      "Lloque",
      "Matalaque",
      "Omate",
      "Puquina",
      "Quinistaquillas",
      "Ubinas",
      "Yunga",
    ],
    Ilo: ["El Algarrobal", "Ilo", "Pacocha"],
    "Mariscal Nieto": [
      "Carumas",
      "Cuchumbaya",
      "Moquegua",
      "Samegua",
      "San Cristobal",
      "Torata",
    ],
  },
  Pasco: {
    "Daniel Alcides Carrion": [
      "Chacayan",
      "Goyllarisquizga",
      "Paucar",
      "San Pedro de Pillao",
      "Santa Ana de Tusi",
      "Tapuc",
      "Vilcabamba",
      "Yanahuanca",
    ],
    Oxapampa: [
      "Chontabamba",
      "Huancabamba",
      "Oxapampa",
      "Palcazu",
      "Pozuzo",
      "Puerto Bermudez",
      "Villa Rica",
    ],
    Pasco: [
      "Chaupimarca",
      "Huachon",
      "Huariaca",
      "Huayllay",
      "Ninacaca",
      "Pallanchacra",
      "Paucartambo",
      "San Fco.De Asis de Yarusyacan",
      "Simon Bolivar",
      "Ticlacayan",
      "Tinyahuarco",
      "Vicco",
      "Yanacancha",
    ],
  },
  Piura: {
    Ayabaca: [
      "Ayabaca",
      "Frias",
      "Jilili",
      "Lagunas",
      "Montero",
      "Pacaipampa",
      "Paimas",
      "Sapillica",
      "Sicchez",
      "Suyo",
    ],
    Huancabamba: [
      "Canchaque",
      "El Carmen de la Frontera",
      "Huancabamba",
      "Huarmaca",
      "Lalaquiz",
      "San Miguel de El Faique",
      "Sondor",
      "Sondorillo",
    ],
    Morropon: [
      "Buenos Aires",
      "Chalaco",
      "Chulucanas",
      "La Matanza",
      "Morropon",
      "Salitral",
      "San Juan de Bigote",
      "Santa Catalina de Mossa",
      "Santo Domingo",
      "Yamango",
    ],
    Paita: [
      "Amotape",
      "Arenal",
      "Colan",
      "La Huaca",
      "Paita",
      "Tamarindo",
      "Vichayal",
    ],
    Piura: [
      "Castilla",
      "Catacaos",
      "Cura Mori",
      "El Tallan",
      "La Arena",
      "La Union",
      "Las Lomas",
      "Piura",
      "Tambo Grande",
    ],
    Sechura: [
      "Bellavista de la Union",
      "Bernal",
      "Cristo Nos Valga",
      "Rinconada Llicuar",
      "Sechura",
      "Vice",
    ],
    Sullana: [
      "Bellavista",
      "Ignacio Escudero",
      "Lancones",
      "Marcavelica",
      "Miguel Checa",
      "Querecotillo",
      "Salitral",
      "Sullana",
    ],
    Talara: [
      "El Alto",
      "La Brea",
      "Lobitos",
      "Los Organos",
      "Mancora",
      "Pariqas",
    ],
  },
  Puno: {
    Azangaro: [
      "Achaya",
      "Arapa",
      "Asillo",
      "Azangaro",
      "Caminaca",
      "Chupa",
      "Jose Domingo Choquehuanca",
      "Muqani",
      "Potoni",
      "Saman",
      "San Anton",
      "San Jose",
      "San Juan de Salinas",
      "Santiago de Pupuja",
      "Tirapata",
    ],
    Carabaya: [
      "Ajoyani",
      "Ayapata",
      "Coasa",
      "Corani",
      "Crucero",
      "Ituata",
      "Macusani",
      "Ollachea",
      "San Gaban",
      "Usicayos",
    ],
    Chucuito: [
      "Desaguadero",
      "Huacullani",
      "Juli",
      "Kelluyo",
      "Pisacoma",
      "Pomata",
      "Zepita",
    ],
    "El Collao": ["Capazo", "Conduriri", "Ilave", "Pilcuyo", "Santa Rosa"],
    Huancane: [
      "Cojata",
      "Huancane",
      "Huatasani",
      "Inchupalla",
      "Pusi",
      "Rosaspata",
      "Taraco",
      "Vilque Chico",
    ],
    Lampa: [
      "Cabanilla",
      "Calapuja",
      "Lampa",
      "Nicasio",
      "Ocuviri",
      "Palca",
      "Paratia",
      "Pucara",
      "Santa Lucia",
      "Vilavila",
    ],
    Melgar: [
      "Antauta",
      "Ayaviri",
      "Cupi",
      "Llalli",
      "Macari",
      "Nuqoa",
      "Orurillo",
      "Santa Rosa",
      "Umachiri",
    ],
    Moho: ["Conima", "Huayrapata", "Moho", "Tilali"],
    Puno: [
      "Acora",
      "Amantani",
      "Atuncolla",
      "Capachica",
      "Chucuito",
      "Coata",
      "Huata",
      "Maqazo",
      "Paucarcolla",
      "Pichacani",
      "Plateria",
      "Puno",
      "San Antonio",
      "Tiquillaca",
      "Vilque",
    ],
    "San Antonio de Putina": [
      "Ananea",
      "Pedro Vilca Apaza",
      "Putina",
      "Quilcapuncu",
      "Sina",
    ],
    "San Roman": ["Cabana", "Cabanillas", "Caracoto", "Juliaca"],
    Sandia: [
      "Alto Inambari",
      "Cuyocuyo",
      "Limbani",
      "Patambuco",
      "Phara",
      "Quiaca",
      "San Juan del Oro",
      "Sandia",
      "Yanahuaya",
    ],
    Yunguyo: [
      "Anapia",
      "Copani",
      "Cuturapi",
      "Ollaraya",
      "Tinicachi",
      "Unicachi",
      "Yunguyo",
    ],
  },
  "San Martin": {
    Bellavista: [
      "Alto Biavo",
      "Bajo Biavo",
      "Bellavista",
      "Huallaga",
      "San Pablo",
      "San Rafael",
    ],
    "El Dorado": [
      "Agua Blanca",
      "San Jose de Sisa",
      "San Martin",
      "Santa Rosa",
      "Shatoja",
    ],
    Huallaga: [
      "Alto Saposoa",
      "El Eslabon",
      "Piscoyacu",
      "Sacanche",
      "Saposoa",
      "Tingo de Saposoa",
    ],
    Lamas: [
      "Alonso de Alvarado",
      "Barranquita",
      "Caynarachi",
      "Cuqumbuqui",
      "Lamas",
      "Pinto Recodo",
      "Rumisapa",
      "San Roque de Cumbaza",
      "Shanao",
      "Tabalosos",
      "Zapatero",
    ],
    "Mariscal Caceres": [
      "Campanilla",
      "Huicungo",
      "Juanjui",
      "Pachiza",
      "Pajarillo",
    ],
    Moyobamba: [
      "Calzada",
      "Habana",
      "Jepelacio",
      "Moyobamba",
      "Soritor",
      "Yantalo",
    ],
    Picota: [
      "Buenos Aires",
      "Caspisapa",
      "Picota",
      "Pilluana",
      "Pucacaca",
      "San Cristobal",
      "San Hilarion",
      "Shamboyacu",
      "Tingo de Ponasa",
      "Tres Unidos",
    ],
    Rioja: [
      "Awajun",
      "Elias Soplin Vargas",
      "Nueva Cajamarca",
      "Pardo Miguel",
      "Posic",
      "Rioja",
      "San Fernando",
      "Yorongos",
      "Yuracyacu",
    ],
    "San Martin": [
      "Alberto Leveau",
      "Cacatachi",
      "Chazuta",
      "Chipurana",
      "El Porvenir",
      "Huimbayoc",
      "Juan Guerra",
      "La Banda de Shilcayo",
      "Morales",
      "Papaplaya",
      "San Antonio",
      "Sauce",
      "Shapaja",
      "Tarapoto",
    ],
    Tocache: ["Nuevo Progreso", "Polvora", "Shunte", "Tocache", "Uchiza"],
  },
  Tacna: {
    Candarave: [
      "Cairani",
      "Camilaca",
      "Candarave",
      "Curibaya",
      "Huanuara",
      "Quilahuani",
    ],
    "Jorge Basadre": ["Ilabaya", "Ite", "Locumba"],
    Tacna: [
      "Alto de la Alianza",
      "Calana",
      "Ciudad Nueva",
      "Cor Gregorio Albarracín",
      "Inclan",
      "Pachia",
      "Palca",
      "Pocollay",
      "Sama",
      "Tacna",
    ],
    Tarata: [
      "Chucatamani",
      "Estique",
      "Estique-Pampa",
      "Sitajara",
      "Susapaya",
      "Tarata",
      "Tarucachi",
      "Ticaco",
    ],
  },
  Tumbes: {
    "Contralmirante Villar": ["Casitas", "Zorritos"],
    Tumbes: [
      "Corrales",
      "La Cruz",
      "Pampas de Hospital",
      "San Jacinto",
      "San Juan de la Virgen",
      "Tumbes",
    ],
    Zarumilla: ["Aguas Verdes", "Matapalo", "Papayal", "Zarumilla"],
  },
  Ucayali: {
    Atalaya: ["Raymondi", "Sepahua", "Tahuania", "Yurua"],
    "Coronel Portillo": [
      "Calleria",
      "Campoverde",
      "Iparia",
      "Masisea",
      "Nueva Requena",
      "Yarinacocha",
    ],
    "Padre Abad": ["Curimana", "Irazola", "Padre Abad"],
    Purus: ["Purus"],
  },
} satisfies Record<
  (typeof departamentos)[number],
  Partial<Record<(typeof provincias)[number], (typeof distritos)[number][]>>
>;
